<!DOCTYPE html>
<html>
  <?php $appControllerModuleHead->render() ?>
  <body>
    <?php $appControllerModuleHeader->render() ?>
    <main>
      <div class="container">
        <div class="row">
          <div class="column width-100">
            <?php $appControllerModuleProfile->render() ?>
            <?php if ($pages) { ?>
              <?php foreach ($pages as $page) { ?>
                <?php $appControllerModulePage->render($page->pageId) ?>
              <?php } ?>
              <?php $appControllerModulePagination->render() ?>
            <?php } else { ?>
              <div class="padding-16 margin-y-8 border-radius-3 background-color-night text-center">
                <h1 class="margin-b-8">
                  <?php echo _('Nothing found') ?>
                </h1>
                <div class="text-color-night">
                  <?php echo _('* share your magnet links to change it') ?>
                </div>
              </div>
            <?php } ?>
          </div>
        </div>
      </div>
    </main>
    <?php $appControllerModuleFooter->render() ?>
  </body>
</html>