<!DOCTYPE html>
<html>
  <?php $appControllerModuleHead->render() ?>
  <body>
    <?php $appControllerModuleHeader->render() ?>
    <main>
      <div class="container">
        <div class="row">
          <div class="column width-100">
            <div class="padding-16 margin-y-8 border-radius-3 background-color-night text-center">
              <h1 class="margin-b-8">
                <?php echo $h1 ?>
              </h1>
              <div>
                <?php echo $text ?>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    <?php $appControllerModuleFooter->render() ?>
  </body>
</html>