<!DOCTYPE html>
<html>
  <?php $appControllerModuleHead->render() ?>
  <body>
    <?php $appControllerModuleHeader->render() ?>
    <main>
      <div class="container">
        <div class="row">
          <div class="column width-100">
            <div class="padding-16 margin-y-8 border-radius-3 background-color-night text-center">
              <div class="margin-b-24 padding-b-16 border-bottom-default">
                <h1 class=""><?php echo _('Welcome, stranger!') ?></h1>
              </div>
              <p class="margin-b-8"><?php echo _('YGGtracker uses Yggdrasil address to identify users without registration') ?></p>
              <p class="margin-b-16"><?php echo _('address below could be shared with independent nodes to allow you manage own content everywhere') ?></p>
              <h2 class="margin-b-16"><?php echo $user->address ?></h2>
              <form name="public" action="welcome" method="post">
                <div class="margin-b-16">
                  <label class="text-color-green margin-y-8 margin-x-4" for="public-1">
                    <input type="radio" id="public-1" name="public" value="1" checked="checked" />
                    <?php echo _('Allow address distribution') ?>
                  </label>
                  <label class="text-color-pink margin-y-8 margin-x-4" for="public-0">
                    <input type="radio" id="public-0" name="public" value="0" />
                    <?php echo _('Keep activity local') ?>
                  </label>
                </div>
                <div class="text-center">
                  <input type="submit" value="<?php echo _('confirm') ?>" />
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </main>
    <?php $appControllerModuleFooter->render() ?>
  </body>
</html>