twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        version: '%app.version%'
        name: '%app.name%'
        theme: '%app.theme%'

when@test:
    twig:
        strict_variables: true
