# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.version: '%env(APP_VERSION)%'
    app.name: '%env(APP_NAME)%'
    app.key: '%env(APP_KEY)%'
    app.pagination: '%env(APP_PAGINATION)%'
    app.trackers: '%env(APP_TRACKERS)%'
    app.crawlers: '%env(APP_CRAWLERS)%'
    app.locales: '%env(APP_LOCALES)%'
    app.themes: '%env(APP_THEMES)%'
    app.locale: '%env(APP_LOCALE)%'
    app.theme: '%env(APP_THEME)%'
    app.sensitive: '%env(APP_SENSITIVE)%'
    app.approved: '%env(APP_APPROVED)%'
    app.yggdrasil: '%env(APP_YGGDRASIL)%'
    app.torrent.size.max: '%env(APP_TORRENT_FILE_SIZE_MAX)%'
    app.torrent.wanted.ftp.enabled: '%env(APP_TORRENT_WANTED_FTP_ENABLED)%'
    app.torrent.wanted.ftp.folder: '%env(APP_TORRENT_WANTED_FTP_FOLDER)%'
    app.torrent.wanted.ftp.approved: '%env(APP_TORRENT_WANTED_FTP_APPROVED_ONLY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Twig\AppExtension:
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension}