    <footer>
      <div class="container">
        <div class="row">
          <div class="column width-100 text-center margin-y-8">
            <?php foreach ($trackers as $i => $tracker) { ?>
              <a href="<?php echo $tracker->announce ?>"><?php echo sprintf('Tracker %s', $i + 1) ?></a>
              /
              <a href="<?php echo $tracker->stats ?>"><?php echo _('Stats') ?></a>
              |
            <?php } ?>
            <a href="faq"><?php echo _('F.A.Q') ?></a>
            |
            <a href="node"><?php echo _('Node') ?></a>
            |
            <a rel="nofollow" href="rss"><?php echo _('RSS') ?></a>
            <?php if (API_EXPORT_ENABLED) { ?>
              |
              <a rel="nofollow" href="api/manifest.json"><?php echo _('API') ?></a>
            <?php } ?>
            |
            <a href="https://github.com/YGGverse/YGGtracker"><?php echo _('GitHub') ?></a>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>