<div class="row">
  <div class="column width-100 text-right">
    <?php echo sprintf(_('page %s / %s'), $pagination->page, $pagination->total) ?>
    <?php if ($pagination->back) { ?>
      <a class="button margin-l-8" rel="nofollow" href="<?php echo $pagination->back ?>">
        <?php echo _('back') ?>
      </a>
    <?php } ?>
    <?php if ($pagination->next) { ?>
      <a class="button margin-l-4" rel="nofollow" href="<?php echo $pagination->next ?>">
        <?php echo _('next') ?>
      </a>
    <?php } ?>
  </div>
</div>