<div class="position-fixed width-160-px margin-l--176 margin-y-8 padding-y-8 background-color-night border-radius-3">
  <?php if ($route == '') { ?>
    <span class="padding-x-16 padding-y-8 display-block  background-color-green cursor-default text-color-white">
      <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
        <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5Z"/>
      </svg>
      <span class="margin-l-4">
        <?php echo _('Home') ?>
      </span>
    </span>
  <?php } else { ?>
    <a class="padding-x-16 padding-y-8 display-block background-color-hover-night-light text-color-default" href="">
      <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
        <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5Z"/>
      </svg>
      <span class="margin-l-4">
        <?php echo _('Home') ?>
      </span>
    </a>
  <?php } ?>
  <?php if ($route == 'submit') { ?>
    <span class="padding-x-16 padding-y-8 display-block  background-color-green cursor-default text-color-white">
      <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
      </svg>
      <span class="margin-l-4">
        <?php echo _('Submit') ?>
      </span>
    </span>
  <?php } else { ?>
    <a class="padding-x-16 padding-y-8 display-block background-color-hover-night-light text-color-default" href="submit">
      <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
      </svg>
      <span class="margin-l-4">
        <?php echo _('Submit') ?>
      </span>
    </a>
  <?php } ?>
  <?php if ($route == 'stars') { ?>
    <span class="padding-x-16 padding-y-8 display-block  background-color-green cursor-default text-color-white">
      <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
        <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
      </svg>
      <span class="margin-l-4">
        <?php echo _('Stars') ?>
      </span>
      <span class="float-right">
        <?php echo $stars ?>
      </span>
    </span>
  <?php } else { ?>
    <a class="padding-x-16 padding-y-8 display-block background-color-hover-night-light text-color-default" href="stars">
      <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
        <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
      </svg>
      <span class="margin-l-4">
        <?php echo _('Stars') ?>
      </span>
      <span class="float-right">
        <?php echo $stars ?>
      </span>
    </a>
  <?php } ?>
  <?php if ($route == 'views') { ?>
    <span class="padding-x-16 padding-y-8 display-block  background-color-green cursor-default text-color-white">
      <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-clock-fill" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
      </svg>
      <span class="margin-l-4">
        <?php echo _('Views') ?>
      </span>
      <span class="float-right">
        <?php echo $views ?>
      </span>
    </span>
  <?php } else { ?>
    <a class="padding-x-16 padding-y-8 display-block background-color-hover-night-light text-color-default" href="views">
      <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-clock-fill" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
      </svg>
      <span class="margin-l-4">
        <?php echo _('Views') ?>
      </span>
      <span class="float-right">
        <?php echo $views ?>
      </span>
    </a>
  <?php } ?>
  <?php if ($route == 'comments') { ?>
    <span class="padding-x-16 padding-y-8 display-block  background-color-green cursor-default text-color-white">
      <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-chat-fill" viewBox="0 0 16 16">
        <path d="M8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6-.097 1.016-.417 2.13-.771 2.966-.079.186.074.394.273.362 2.256-.37 3.597-.938 4.18-1.234A9.06 9.06 0 0 0 8 15z"/>
      </svg>
      <span class="margin-l-4">
        <?php echo _('Comments') ?>
      </span>
      <span class="float-right">
        <?php echo $comments ?>
      </span>
    </span>
  <?php } else { ?>
    <a class="padding-x-16 padding-y-8 display-block background-color-hover-night-light text-color-default" href="comments">
      <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-chat-fill" viewBox="0 0 16 16">
        <path d="M8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6-.097 1.016-.417 2.13-.771 2.966-.079.186.074.394.273.362 2.256-.37 3.597-.938 4.18-1.234A9.06 9.06 0 0 0 8 15z"/>
      </svg>
      <span class="margin-l-4">
        <?php echo _('Comments') ?>
      </span>
      <span class="float-right">
        <?php echo $comments ?>
      </span>
    </a>
  <?php } ?>
  <?php if ($route == 'downloads') { ?>
    <span class="padding-x-16 padding-y-8 display-block  background-color-green cursor-default text-color-white">
      <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-arrow-down-circle-fill" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v5.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V4.5z"/>
      </svg>
      <span class="margin-l-4">
        <?php echo _('Downloads') ?>
      </span>
      <span class="float-right">
        <?php echo $downloads ?>
      </span>
    </span>
  <?php } else { ?>
    <a class="padding-x-16 padding-y-8 display-block background-color-hover-night-light text-color-default" href="downloads">
      <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-arrow-down-circle-fill" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v5.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V4.5z"/>
      </svg>
      <span class="margin-l-4">
        <?php echo _('Downloads') ?>
      </span>
      <span class="float-right">
        <?php echo $downloads ?>
      </span>
    </a>
  <?php } ?>
  <?php if ($route == 'editions') { ?>
    <span class="padding-x-16 padding-y-8 display-block  background-color-green cursor-default text-color-white">
      <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-file-diff-fill" viewBox="0 0 16 16">
        <path d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM8.5 4.5V6H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V7H6a.5.5 0 0 1 0-1h1.5V4.5a.5.5 0 0 1 1 0zM6 10h4a.5.5 0 0 1 0 1H6a.5.5 0 0 1 0-1z"/>
      </svg>
      <span class="margin-l-4">
        <?php echo _('Editions') ?>
      </span>
      <span class="float-right">
        <?php echo $editions ?>
      </span>
    </span>
  <?php } else { ?>
    <a class="padding-x-16 padding-y-8 display-block background-color-hover-night-light text-color-default" href="editions">
      <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-file-diff-fill" viewBox="0 0 16 16">
        <path d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM8.5 4.5V6H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V7H6a.5.5 0 0 1 0-1h1.5V4.5a.5.5 0 0 1 1 0zM6 10h4a.5.5 0 0 1 0 1H6a.5.5 0 0 1 0-1z"/>
      </svg>
      <span class="margin-l-4">
        <?php echo _('Editions') ?>
      </span>
      <span class="float-right">
        <?php echo $editions ?>
      </span>
    </a>
  <?php } ?>
</div>